import type { Resource } from '@/types/resources';

export const mockResources: Resource[] = [
  // Free Resources
  {
    id: '1',
    title: 'Cessna 172 Preflight Checklist',
    description: 'Comprehensive preflight inspection checklist for Cessna 172 aircraft. Includes exterior walkaround, cockpit checks, and engine start procedures.',
    category: 'checklist',
    subcategory: 'preflight',
    fileUrl: '/resources/cessna-172-preflight.pdf',
    fileSize: 245760,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 1250,
    tags: ['cessna', 'preflight', 'inspection', 'safety', 'checklist'],
    metadata: {
      aircraftType: ['Cessna 172'],
      version: '2.1',
      lastUpdated: '2024-01-15',
    },
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Aviation Phonetic Alphabet Reference',
    description: 'Quick reference card for the ICAO phonetic alphabet, numbers, and common aviation phrases used in radio communications.',
    category: 'reference',
    subcategory: 'communications',
    fileUrl: '/resources/phonetic-alphabet.pdf',
    fileSize: 128000,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 2100,
    tags: ['communications', 'radio', 'phonetic', 'alphabet', 'ATC'],
    metadata: {
      relatedAcsCodes: ['PA.III.A.K1'],
    },
    isActive: true,
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
  {
    id: '3',
    title: 'VFR Weather Minimums Chart',
    description: 'Visual guide to VFR weather minimums for different airspace classes. Includes cloud clearance and visibility requirements.',
    category: 'weather',
    subcategory: 'vfr',
    fileUrl: '/resources/vfr-weather-minimums.pdf',
    fileSize: 196608,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 1890,
    tags: ['weather', 'VFR', 'minimums', 'airspace', 'visibility'],
    metadata: {
      relatedAcsCodes: ['PA.I.C.K1', 'PA.I.E.K1'],
    },
    isActive: true,
    createdAt: '2023-12-20T09:30:00Z',
    updatedAt: '2024-01-10T14:15:00Z',
  },
  {
    id: '4',
    title: 'Aviation Regulation Mnemonics',
    description: 'Memory aids for important aviation regulations including required documents, equipment, and currency requirements.',
    category: 'mnemonics',
    fileUrl: '/resources/aviation-mnemonics.pdf',
    fileSize: 163840,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 3200,
    tags: ['regulations', 'memory', 'study', 'FAR', 'mnemonics'],
    metadata: {
      relatedAcsCodes: ['PA.I.A.K1', 'PA.I.A.K2'],
    },
    isActive: true,
    createdAt: '2023-11-15T12:00:00Z',
    updatedAt: '2024-01-05T16:20:00Z',
  },
  {
    id: '5',
    title: 'Basic Airport Markings Guide',
    description: 'Visual reference for understanding runway, taxiway, and ramp markings at airports. Essential for safe ground operations.',
    category: 'airport-diagrams',
    subcategory: 'markings',
    fileUrl: '/resources/airport-markings-guide.pdf',
    fileSize: 524288,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 980,
    tags: ['airport', 'markings', 'runway', 'taxiway', 'safety'],
    metadata: {
      relatedAcsCodes: ['PA.III.B.K1'],
    },
    isActive: true,
    createdAt: '2024-01-08T11:00:00Z',
    updatedAt: '2024-01-08T11:00:00Z',
  },
  // Premium Resources
  {
    id: '6',
    title: 'IFR Approach Plate Interpretation Guide',
    description: 'Comprehensive guide to reading and interpreting IFR approach plates. Includes symbology, minimums, and profile views.',
    category: 'study-guide',
    subcategory: 'ifr',
    fileUrl: '/resources/ifr-approach-plates.pdf',
    fileSize: 1048576,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 456,
    tags: ['IFR', 'approaches', 'plates', 'navigation', 'instrument'],
    metadata: {
      relatedAcsCodes: ['IR.I.B.K1', 'IR.I.B.K2'],
      version: '3.0',
    },
    isActive: true,
    createdAt: '2024-01-05T16:45:00Z',
    updatedAt: '2024-01-25T11:20:00Z',
  },
  {
    id: '7',
    title: 'Weather Briefing Decoder & Analysis Tool',
    description: 'Advanced guide to decoding METARs, TAFs, and weather charts. Includes practice exercises and real-world examples.',
    category: 'reference',
    subcategory: 'weather',
    fileUrl: '/resources/weather-briefing-decoder.pdf',
    fileSize: 786432,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 890,
    tags: ['weather', 'METAR', 'TAF', 'briefing', 'decode'],
    metadata: {
      relatedAcsCodes: ['PA.I.C.K1', 'PA.I.C.K2'],
      version: '2.5',
    },
    isActive: true,
    createdAt: '2024-01-10T14:30:00Z',
    updatedAt: '2024-01-20T09:15:00Z',
  },
  {
    id: '8',
    title: 'Complete Performance Charts Collection',
    description: 'Collection of performance charts for popular training aircraft including takeoff, landing, cruise, and climb performance.',
    category: 'reference',
    subcategory: 'performance',
    fileUrl: '/resources/performance-charts-collection.pdf',
    fileSize: 2097152,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 567,
    tags: ['performance', 'charts', 'takeoff', 'landing', 'weight-balance'],
    metadata: {
      aircraftType: ['Cessna 172', 'Piper Cherokee', 'Cessna 152'],
      relatedAcsCodes: ['PA.I.F.K1'],
    },
    isActive: true,
    createdAt: '2024-01-12T13:00:00Z',
    updatedAt: '2024-01-12T13:00:00Z',
  },
  {
    id: '9',
    title: 'Emergency Procedures Quick Reference',
    description: 'Comprehensive emergency procedures for engine failures, electrical failures, and other critical situations.',
    category: 'checklist',
    subcategory: 'emergency',
    fileUrl: '/resources/emergency-procedures.pdf',
    fileSize: 393216,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 1200,
    tags: ['emergency', 'procedures', 'safety', 'checklist', 'critical'],
    metadata: {
      aircraftType: ['General Aviation'],
      relatedAcsCodes: ['PA.IX.A.K1', 'PA.IX.B.K1'],
    },
    isActive: true,
    createdAt: '2024-01-20T12:00:00Z',
    updatedAt: '2024-01-20T12:00:00Z',
  },
  {
    id: '10',
    title: 'Weight & Balance Calculator Template',
    description: 'Interactive Excel template for calculating weight and balance for various aircraft. Includes CG envelope charts.',
    category: 'interactive',
    subcategory: 'planning',
    fileUrl: '/resources/weight-balance-calculator.xlsx',
    fileSize: 245760,
    fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    accessLevel: 'premium',
    downloadCount: 780,
    tags: ['weight', 'balance', 'CG', 'calculator', 'planning'],
    metadata: {
      aircraftType: ['Cessna 172', 'Piper Cherokee'],
      relatedAcsCodes: ['PA.I.F.K1'],
    },
    isActive: true,
    createdAt: '2024-01-18T10:30:00Z',
    updatedAt: '2024-01-18T10:30:00Z',
  },
  {
    id: '11',
    title: 'Cross-Country Planning Worksheet',
    description: 'Detailed worksheet for planning cross-country flights including nav log, weather considerations, and fuel planning.',
    category: 'study-guide',
    subcategory: 'navigation',
    fileUrl: '/resources/cross-country-planning.pdf',
    fileSize: 458752,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 620,
    tags: ['navigation', 'cross-country', 'planning', 'fuel', 'weather'],
    metadata: {
      relatedAcsCodes: ['PA.I.D.K1', 'PA.I.D.K2'],
    },
    isActive: true,
    createdAt: '2024-01-22T14:00:00Z',
    updatedAt: '2024-01-22T14:00:00Z',
  },
  // Exclusive Resources
  {
    id: '12',
    title: 'CFI Teaching Techniques Masterclass',
    description: 'Advanced teaching techniques for flight instructors including scenario-based training and learner-centered grading.',
    category: 'study-guide',
    subcategory: 'instruction',
    fileUrl: '/resources/cfi-teaching-techniques.pdf',
    fileSize: 1572864,
    fileType: 'application/pdf',
    accessLevel: 'exclusive',
    downloadCount: 234,
    tags: ['CFI', 'teaching', 'instruction', 'techniques', 'advanced'],
    metadata: {
      version: '4.0',
    },
    isActive: true,
    createdAt: '2024-01-25T16:00:00Z',
    updatedAt: '2024-01-25T16:00:00Z',
  },
  {
    id: '13',
    title: 'Advanced Weather Analysis Toolkit',
    description: 'Professional-grade weather analysis tools including frontal analysis, turbulence prediction, and icing forecasts.',
    category: 'weather',
    subcategory: 'advanced',
    fileUrl: '/resources/advanced-weather-toolkit.pdf',
    fileSize: 2621440,
    fileType: 'application/pdf',
    accessLevel: 'exclusive',
    downloadCount: 189,
    tags: ['weather', 'advanced', 'analysis', 'professional', 'forecasting'],
    metadata: {
      relatedAcsCodes: ['PA.I.C.K2'],
      version: '5.2',
    },
    isActive: true,
    createdAt: '2024-01-28T09:00:00Z',
    updatedAt: '2024-01-28T09:00:00Z',
  },
  {
    id: '14',
    title: 'Complete FAR/AIM Study Package',
    description: 'Comprehensive study package with highlighted regulations, quick reference guides, and practice scenarios.',
    category: 'regulations',
    subcategory: 'complete',
    fileUrl: '/resources/far-aim-study-package.pdf',
    fileSize: 4194304,
    fileType: 'application/pdf',
    accessLevel: 'exclusive',
    downloadCount: 156,
    tags: ['FAR', 'AIM', 'regulations', 'complete', 'study'],
    metadata: {
      relatedAcsCodes: ['PA.I.A.K1', 'PA.I.A.K2'],
      version: '2024.1',
    },
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T12:00:00Z',
  },
  {
    id: '15',
    title: 'Professional Pilot Interview Prep Guide',
    description: 'Exclusive guide for airline and corporate pilot interviews including common questions, simulator tips, and HR strategies.',
    category: 'study-guide',
    subcategory: 'career',
    fileUrl: '/resources/pilot-interview-prep.pdf',
    fileSize: 917504,
    fileType: 'application/pdf',
    accessLevel: 'exclusive',
    downloadCount: 278,
    tags: ['interview', 'career', 'airline', 'professional', 'preparation'],
    metadata: {
      version: '2024',
    },
    isActive: true,
    createdAt: '2024-01-26T11:00:00Z',
    updatedAt: '2024-01-26T11:00:00Z',
  },
  // More Free Resources
  {
    id: '16',
    title: 'Student Pilot Quick Reference Card',
    description: 'Essential information for student pilots including airspace, right-of-way rules, and basic weather minimums.',
    category: 'reference',
    subcategory: 'student',
    fileUrl: '/resources/student-pilot-reference.pdf',
    fileSize: 98304,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 1567,
    tags: ['student', 'reference', 'basics', 'airspace', 'rules'],
    metadata: {
    },
    isActive: true,
    createdAt: '2023-12-10T08:00:00Z',
    updatedAt: '2024-01-02T10:00:00Z',
  },
  {
    id: '17',
    title: 'Radio Communication Script Examples',
    description: 'Common radio communication scripts for various phases of flight including pattern work and cross-country.',
    category: 'reference',
    subcategory: 'communications',
    fileUrl: '/resources/radio-scripts.pdf',
    fileSize: 131072,
    fileType: 'application/pdf',
    accessLevel: 'free',
    downloadCount: 1234,
    tags: ['radio', 'communications', 'scripts', 'ATC', 'phraseology'],
    metadata: {
      relatedAcsCodes: ['PA.III.A.K1'],
    },
    isActive: true,
    createdAt: '2024-01-03T15:30:00Z',
    updatedAt: '2024-01-03T15:30:00Z',
  },
  // More Premium Resources
  {
    id: '18',
    title: 'Night Flying Operations Guide',
    description: 'Comprehensive guide to night flying including physiological factors, lighting, and emergency procedures.',
    category: 'study-guide',
    subcategory: 'night',
    fileUrl: '/resources/night-flying-guide.pdf',
    fileSize: 655360,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 345,
    tags: ['night', 'flying', 'vision', 'lighting', 'safety'],
    metadata: {
      relatedAcsCodes: ['PA.I.A.K1'],
    },
    isActive: true,
    createdAt: '2024-01-24T18:00:00Z',
    updatedAt: '2024-01-24T18:00:00Z',
  },
  {
    id: '19',
    title: 'Mountain Flying Techniques',
    description: 'Essential techniques for safe mountain flying including density altitude, terrain, and weather considerations.',
    category: 'study-guide',
    subcategory: 'specialty',
    fileUrl: '/resources/mountain-flying.pdf',
    fileSize: 1310720,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 267,
    tags: ['mountain', 'terrain', 'density-altitude', 'weather', 'techniques'],
    metadata: {
      relatedAcsCodes: ['PA.I.F.K1'],
    },
    isActive: true,
    createdAt: '2024-01-27T12:00:00Z',
    updatedAt: '2024-01-27T12:00:00Z',
  },
  {
    id: '20',
    title: 'Glass Cockpit Transition Guide',
    description: 'Transition guide for pilots moving from traditional instruments to glass cockpit avionics systems.',
    category: 'study-guide',
    subcategory: 'avionics',
    fileUrl: '/resources/glass-cockpit-guide.pdf',
    fileSize: 983040,
    fileType: 'application/pdf',
    accessLevel: 'premium',
    downloadCount: 432,
    tags: ['glass-cockpit', 'avionics', 'G1000', 'transition', 'technology'],
    metadata: {
      aircraftType: ['Cessna 172 G1000', 'Cirrus SR22'],
    },
    isActive: true,
    createdAt: '2024-01-29T10:00:00Z',
    updatedAt: '2024-01-29T10:00:00Z',
  },
];
