import { setRequestLocale } from 'next-intl/server';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default async function FourForcesLesson(props: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  setRequestLocale(locale);

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Breadcrumb Navigation */}
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Link href={`/${locale}/handbook/private-pilot`} className="hover:text-foreground">
          Private Pilot
        </Link>
        <span>›</span>
        <Link href={`/${locale}/handbook/private-pilot/principles-of-flight`} className="hover:text-foreground">
          Principles of Flight
        </Link>
        <span>›</span>
        <span>The Four Forces of Flight</span>
      </div>

      {/* Lesson Header */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold">The Four Forces of Flight</h1>
            <p className="text-muted-foreground mt-1">
              Understanding lift, weight, thrust, and drag
            </p>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <span className="text-muted-foreground">Lesson 1 of 8</span>
            <span className="text-muted-foreground">•</span>
            <span className="text-muted-foreground">20 min</span>
          </div>
        </div>

        {/* Progress indicator */}
        <div className="w-full bg-muted rounded-full h-1">
          <div className="bg-primary h-1 rounded-full w-1/8" />
        </div>
      </div>

      {/* Lesson Content */}
      <div className="prose prose-slate max-w-none">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="text-2xl">⚖️</span>
              Introduction
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-base leading-relaxed">
              Flight is possible because of the interaction between four fundamental forces. These forces must be
              understood by every pilot to safely control an aircraft. The four forces are:
            </p>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="p-4 bg-primary/5 rounded-lg border border-primary/20">
                <h3 className="font-semibold text-primary mb-2">🔺 Lift</h3>
                <p className="text-sm">The upward force generated by the wing that opposes weight</p>
              </div>
              <div className="p-4 bg-secondary/5 rounded-lg border border-secondary/20">
                <h3 className="font-semibold text-secondary-foreground mb-2">⬇️ Weight</h3>
                <p className="text-sm">The downward force due to gravity acting on the aircraft's mass</p>
              </div>
              <div className="p-4 bg-accent/5 rounded-lg border border-accent/20">
                <h3 className="font-semibold text-accent-foreground mb-2">➡️ Thrust</h3>
                <p className="text-sm">The forward force generated by the propeller or jet engine</p>
              </div>
              <div className="p-4 bg-muted/50 rounded-lg border border-muted">
                <h3 className="font-semibold text-foreground mb-2">⬅️ Drag</h3>
                <p className="text-sm">The rearward force that opposes the aircraft's motion through the air</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="text-2xl">📐</span>
              Force Relationships
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <h3 className="text-lg font-semibold">Steady, Level Flight</h3>
            <p>
              For an aircraft to maintain steady, level flight, the forces must be in equilibrium:
            </p>

            <div className="bg-muted/30 p-4 rounded-lg">
              <div className="grid gap-2 md:grid-cols-2 text-center">
                <div className="p-3 bg-background rounded border">
                  <p className="font-mono text-sm">Lift = Weight</p>
                </div>
                <div className="p-3 bg-background rounded border">
                  <p className="font-mono text-sm">Thrust = Drag</p>
                </div>
              </div>
            </div>

            <h3 className="text-lg font-semibold">Climbing Flight</h3>
            <p>
              To climb, lift must exceed weight, and thrust must exceed drag to overcome the additional
              drag component created by the climb angle.
            </p>

            <h3 className="text-lg font-semibold">Descending Flight</h3>
            <p>
              In a descent, weight exceeds lift. The component of weight acting along the flight path
              helps overcome drag, so less thrust is required.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="text-2xl">🎯</span>
              Key Takeaways
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1">•</span>
                <span>The four forces always act on an aircraft in flight: lift, weight, thrust, and drag</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1">•</span>
                <span>Force equilibrium is required for steady, level flight</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1">•</span>
                <span>Changing the relationship between forces results in climbing or descending flight</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary mt-1">•</span>
                <span>Understanding these forces is fundamental to all flight operations</span>
              </li>
            </ul>
          </CardContent>
        </Card>
      </div>

      {/* Navigation and Actions */}
      <div className="flex flex-col sm:flex-row gap-3 pt-6 border-t">
        <Button asChild variant="outline">
          <Link href={`/${locale}/handbook/private-pilot/principles-of-flight`}>
            ← Back to Unit
          </Link>
        </Button>

        <div className="flex-1" />

        <Button asChild>
          <Link href={`/${locale}/handbook/private-pilot/principles-of-flight/four-forces/quiz`}>
            Take Quiz →
          </Link>
        </Button>
      </div>

      {/* Progress Footer */}
      <Card className="bg-primary/5 border-primary/20">
        <CardContent className="p-4">
          <div className="flex items-center justify-between text-sm">
            <span className="text-primary font-medium">Lesson Progress</span>
            <span className="text-muted-foreground">Next: Airfoil Theory and Design</span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
